baseURL = 'https://yangshuangfei.github.io/'
languageCode = "zh-cn"
title = "Stitch Blog"
theme = "PaperMod"

[pagination]
pagerSize = 10

[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML"]

[params]
defaultTheme = "auto"

ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowSearchPage = true

summaryLength = 120

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 100
threshold = 0.4
minMatchCharLength = 2
limit = 10

# 关键：不要搜索 content
keys = ["title", "summary"]

[[menu.main]]
identifier = "search"
name = "搜索"
url = "/search/"
weight = 10